version: "3.1"
networks:
  docker-network:
services:
  #nginx я добавил для себя,чтобы проверить работоспособность конфигурации.
  #adminer тоже
  nginx:
    image:
      nginx
    ports:
      - "84:80"
    volumes:
      - ./:/var/www/html
      - ./sourcefile/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network
  docker-php-fpm:
    ports:
    - 9000:9000
    build:
      context: ./sourcefile/php
    volumes:
    - ./:/var/www/html/
    networks:
      - docker-network
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: laravel_test_db
      POSTGRES_USER: laravel_test_user
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./sourcefile/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - docker-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - docker-network
