version: "3.1"
networks:
  docker-network:
services:
  docker-php-fpm:
    build:
      context: ./sourcefile/php
    volumes:
    - ./:/var/www/html/
    #working_dir: /app
    networks:
      - docker-network
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: laravel_test_db
      POSTGRES_USER: laravel_test_user
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - docker-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - docker-network
